baseURL = 'https://bigfa.github.io/'
languageCode = 'zh-cn'
timezone = 'Asia/Shanghai'
defaultContentLanguage = 'zh-cn'
theme = 'farallon'


[langusges]
[languages.en]
  title = "Untitled"
  languageName = "English"
  contentDir = 'content/en'
  [languages.en.menu]
    [[languages.en.menu.main]]
    name="Gears"
    url="/en/gears/"
    weight="2"
    [[languages.en.menu.main]]
    name="Movies"
    url="/en/movies/"
    weight="1"
    [[languages.en.menu.main]]
    name="Categories"
    url="/en/categories/"
    weight="1"
    [[languages.en.menu.main]]
    name="Tags"
    url="/en/tags/"
    weight="1"
    [[languages.en.menu.main]]
    name="About"
    url="/en/about/"
    weight="3"
    [[languages.en.menu.main]]
    name="Stories"
    url="/en/story/"
    weight="1"

[languages.zh-cn]
  title = "Untitled"
  languageName = "简体中文"
  contentDir = 'content/zh-cn'
  [languages.zh-cn.menu]
    [[languages.zh-cn.menu.main]]
    name="设备"
    url="/gears/"
    weight="1"
    [[languages.zh-cn.menu.main]]
    name="书影音"
    url="/movies/"
    weight="1"
    [[languages.zh-cn.menu.main]]
    name="分类"
    url="/categories/"
    weight="1"
    [[languages.zh-cn.menu.main]]
    name="标签"
    url="/tags/"
    weight="1"
    [[languages.zh-cn.menu.main]]
    name="文章"
    url="/story/"
    weight="1"

[taxonomies]
  category = 'categories'
  tag = 'tags'

[Params]
  search= true
  description = 'A simple and fast blog framework written in Go.'
  toc = true
  mainSections = ['story','memo']
  indexName = 'bigfa'
  searchKey = 'b0825b184f45c084e31770fbcc9261f2'
  searchAPPID = 'FX1CAS2SD8'
  showAuthor = true
  authorName = 'bigfa'
  authorDescription = 'computer loser'
  authorAvatar = 'https://secure.gravatar.com/avatar/2fd7e2e17a671f8e3fade0706e0a667e?s=128&d=mm&r=g'
  commentDomain = 'https://fatesinger.com/__api/v1'
  telegram = 'https://t.me/s/fatesinger'
  feed = '/index.xml'
  twitter = 'https://twitter.com/fatesinger'
  instagram = 'https://www.instagram.com/fatesinger/'
  github = 'https://github.com/bigfa'
  footer_sns = true

[outputs]
  home = [ "HTML","JSON","RSS","SITEMAP"]
  page = ["HTML"]


[markup.tableOfContents]
    endLevel = 5
    startLevel = 3